server:
  port: 1226
  servlet:
    context-path: /purepanel

spring:
  application:
    name: purepanel-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purepanel?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 122699
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

mybatis-plus:
  mapper-locations: classpath*:cn/yzdoit/purepanel/mapper/xml/*Mapper.xml
  global-config:
    banner: false
  configuration:
    log-impl: cn.yzdoit.purepanel.log.MyBatisLogImpl

purepanel:
  res-exception-enabled: true
  local-object-store-base-path: C:/Users/bell1/Documents/dev
  login-config:
    single-session-login-enabled: false
    login-code-verify-enabled: false

logging:
  level:
    cn.yzdoit.purepanel.log.MyBatisLogImpl: trace